# Generated by Django 4.2.1 on 2023-06-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunaapi', '0002_genre_name_alter_genre_description_alter_genre_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='song_count',
        ),
    ]
